# Generated by Django 4.0.4 on 2022-05-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
